/**
 * Input Schema for AI Analysis Module
 *
 * Every website analysis request should follow this structure.
 */

const { z } = require("zod");

/**
 * ------------------------------
 * Technical Analysis
 * ------------------------------
 * Generated by Technical Services
 */
const TechnicalSchema = z.object({
  https: z.boolean(),

  ssl: z.object({
    valid: z.boolean(),
    issuer: z.string().optional(),
    expiresOn: z.string().optional(),
  }),

  domain: z.object({
    ageInDays: z.number(),
    registrar: z.string(),
    createdOn: z.string(),
    expiresOn: z.string(),
  }),

  dns: z.object({
    ipAddress: z.string(),
    hostingProvider: z.string().optional(),
    records: z.record(z.any()).optional(),
  }),

  redirects: z.array(z.string()).default([]),

  robotsTxt: z.boolean(),

  sitemap: z.boolean(),
});

/**
 * ------------------------------
 * Reputation Analysis
 * ------------------------------
 * Generated by Reputation Services
 */
const ReputationSchema = z.object({
  reddit: z.object({
    mentions: z.number(),
    summary: z.string(),
  }),

  virusTotal: z.object({
    malicious: z.number(),
    suspicious: z.number(),
    harmless: z.number(),
  }),

  phishTank: z.object({
    listed: z.boolean(),
  }),

  scamAdviser: z.object({
    trustScore: z.number(),
  }),

  urlHaus: z.object({
    listed: z.boolean(),
  }),

  abuseIPDB: z.object({
    score: z.number(),
  }),
});

/**
 * ------------------------------
 * Website Data
 * ------------------------------
 * Generated by Scraper
 */
const WebsiteSchema = z.object({
  url: z.string().url(),

  html: z.string(),

  title: z.string(),

  meta: z.object({
    description: z.string().optional(),
    keywords: z.array(z.string()).default([]),
    author: z.string().optional(),
  }),

  visibleText: z.string(),

  forms: z.array(z.any()).default([]),

  links: z.array(z.any()).default([]),

  buttons: z.array(z.any()).default([]),

  images: z.array(z.any()).default([]),

  scripts: z.array(z.any()).default([]),
});

/**
 * ------------------------------
 * AI Input Schema
 * ------------------------------
 */
const AnalysisInputSchema = z.object({
  technical: TechnicalSchema,

  reputation: ReputationSchema,

  website: WebsiteSchema,

  screenshot: z.string().nullable().optional(),
});

module.exports = {
  AnalysisInputSchema,
};